"""fix error

Revision ID: 47bfaf22e9ab
Revises: 
Create Date: 2018-11-04 15:00:40.510293

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '47bfaf22e9ab'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('classes',
    sa.Column('class_id', sa.Integer(), nullable=False),
    sa.Column('class_name', sa.String(length=128), nullable=True),
    sa.Column('class_token', sa.String(length=128), nullable=True),
    sa.Column('class_teacher', sa.Integer(), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('last_seen', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('class_id'),
    sa.UniqueConstraint('class_token')
    )
    op.create_index(op.f('ix_classes_class_name'), 'classes', ['class_name'], unique=False)
    op.create_index(op.f('ix_classes_class_teacher'), 'classes', ['class_teacher'], unique=False)
    op.create_table('students',
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('rfid_id', sa.String(length=64), nullable=True),
    sa.Column('student_number', sa.String(length=64), nullable=True),
    sa.Column('student_name', sa.String(length=64), nullable=True),
    sa.Column('student_nickname', sa.String(length=64), nullable=False),
    sa.Column('curr_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('student_id'),
    sa.UniqueConstraint('student_id')
    )
    op.create_index(op.f('ix_students_rfid_id'), 'students', ['rfid_id'], unique=True)
    op.create_index(op.f('ix_students_student_name'), 'students', ['student_name'], unique=True)
    op.create_index(op.f('ix_students_student_number'), 'students', ['student_number'], unique=True)
    op.create_table('timetable',
    sa.Column('time_id', sa.Integer(), nullable=False),
    sa.Column('time_class_name', sa.String(length=128), nullable=True),
    sa.Column('time_class_id', sa.Integer(), nullable=True),
    sa.Column('time_student_id', sa.Integer(), nullable=True),
    sa.Column('time_time', sa.DateTime(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('time_id'),
    sa.UniqueConstraint('time_id')
    )
    op.create_index(op.f('ix_timetable_time_class_id'), 'timetable', ['time_class_id'], unique=False)
    op.create_index(op.f('ix_timetable_time_class_name'), 'timetable', ['time_class_name'], unique=False)
    op.create_index(op.f('ix_timetable_time_student_id'), 'timetable', ['time_student_id'], unique=False)
    op.create_table('student_identifier',
    sa.Column('class_id', sa.Integer(), nullable=True),
    sa.Column('student_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['class_id'], ['classes.class_id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.student_id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('student_identifier')
    op.drop_index(op.f('ix_timetable_time_student_id'), table_name='timetable')
    op.drop_index(op.f('ix_timetable_time_class_name'), table_name='timetable')
    op.drop_index(op.f('ix_timetable_time_class_id'), table_name='timetable')
    op.drop_table('timetable')
    op.drop_index(op.f('ix_students_student_number'), table_name='students')
    op.drop_index(op.f('ix_students_student_name'), table_name='students')
    op.drop_index(op.f('ix_students_rfid_id'), table_name='students')
    op.drop_table('students')
    op.drop_index(op.f('ix_classes_class_teacher'), table_name='classes')
    op.drop_index(op.f('ix_classes_class_name'), table_name='classes')
    op.drop_table('classes')
    # ### end Alembic commands ###
