"""add class_name

Revision ID: a0355c3e40e1
Revises: b2a24720e686
Create Date: 2018-10-20 16:55:24.576550

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a0355c3e40e1'
down_revision = 'b2a24720e686'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('timetable', sa.Column('time_class_name', sa.String(length=128), nullable=True))
    op.create_index(op.f('ix_timetable_time_class_name'), 'timetable', ['time_class_name'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_timetable_time_class_name'), table_name='timetable')
    op.drop_column('timetable', 'time_class_name')
    # ### end Alembic commands ###
